### ISSUE TITLE
Update for Spark v2.4

### ISSUE THREAD

**Issue by jtlz2** [UNINETT/kubernetes-apps#1]
@gurvindersingh This repo is the closest I have found to get Jupyter+Spark running on k8s. Amazing find - thank you!

Is there the remotest chance of an update for v2.4?

I put out a stackoverflow question at https://stackoverflow.com/questions/55098343/spark-k8s-how-do-i-install-spark-2-4-on-an-existing-kubernetes-cluster-in-clie

Thanks again!

**Comment by gurvindersingh** [comment]
I should have archived this repo.. development has moved to this repo https://github.com/Uninett/helm-charts there you can find spark, notebook and other useful charts.
