### ISSUE TITLE
oauth-proxy-config error

### ISSUE THREAD

**Issue by jtlz2** [UNINETT/kubernetes-apps#2]
@gurvindersingh As written, my spark-master and jupyter-notebook pods won't start because of the following event:

`MountVolume.SetUp failed for volume "oauth-proxy-config" : configmaps "spark-master-oauth-proxy" not found`

Any ideas on why this is not working?

The pv/pvc are Available/Bound respectively.

**Comment by gurvindersingh** [comment]
Refer another repo here https://github.com/Uninett/helm-charts
