### ISSUE TITLE
Change the value of spark.driver.maxResultSize?

### ISSUE THREAD

**Issue by ghost** [UNINETT/kubernetes-apps#3]
In the [config file](https://github.com/Uninett/kubernetes-apps/blob/2d307bb7f10451f7ddfdf9141cd4d8d5ca50e450/spark/dockerfiles/base/spark-defaults.conf), **spark.driver.maxResultSize** is set to 0, which means unlimited.

The Spark [official document](https://spark.apache.org/docs/latest/configuration.html) recommends to set **spark.driver.maxResultSize** to a proper limited value. 
"Having a high limit may cause out-of-memory errors in driver (depends on spark.driver.memory and memory overhead of objects in JVM)."  Setting a proper limit can protect the driver from out-of-memory errors. 

I wonder if the value of this parameter need to be changed. Thanks.

**Comment by gurvindersingh** [comment]
Refer another repo here https://github.com/Uninett/helm-charts
